# Generated by Django 3.2.16 on 2023-01-13 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the inspector project', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the inspector project', max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the inspector project was created')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the inspector project deleted?')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Date and time when the inspector project was deleted', null=True)),
                ('inspector', models.ForeignKey(help_text='User who created the inspector project', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the defect', max_length=255, unique=True)),
                ('body', models.TextField(help_text='Description of the defect', max_length=255)),
                ('status', models.CharField(choices=[('C', 'Completed'), ('O', 'Overdue'), ('P', 'Pending'), ('U', 'Upcoming'), ('A', 'Active'), ('X', 'Cancelled'), ('N', 'Not Started')], default='P', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the defect was created')),
                ('images', models.ImageField(blank=True, help_text='Image of the defect(s)', null=True, upload_to='inspector/defect/')),
                ('due_date', models.DateField(blank=True, help_text='Date when the defect should be Fixed!', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the defect removed?')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Date and time when the inspector project was deleted', null=True)),
                ('author', models.ForeignKey(help_text='User who created the defect', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project where the defect was found', on_delete=django.db.models.deletion.CASCADE, to='inspector.inspection')),
            ],
        ),
    ]
