# Generated by Django 3.2.16 on 2023-01-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='title',
            field=models.CharField(help_text='Title of the defect', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='name',
            field=models.CharField(help_text='Name of the inspector project', max_length=30, unique=True),
        ),
    ]
