# Generated by Django 3.2.16 on 2023-01-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_auto_20230114_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag', max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='defect',
            name='images',
            field=models.ImageField(blank=True, help_text='Image of the defect', null=True, upload_to='inspector/defect/'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='name',
            field=models.CharField(help_text='Name of the inspector project', max_length=30),
        ),
    ]
