# Generated by Django 3.2.16 on 2023-01-17 07:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0003_auto_20230115_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description of the defect', null=True),
        ),
    ]
