# Generated by Django 4.0.2 on 2022-02-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0003_dimension_description_alter_dimension_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
