# Generated by Django 4.0.2 on 2022-02-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0006_payee_dimension_created_on_project_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dimension.project'),
        ),
    ]
