# Generated by Django 4.0.2 on 2022-02-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0007_expense_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='author',
        ),
    ]
