# Generated by Django 4.0.2 on 2022-02-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0008_rename_creator_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
