# Generated by Django 4.0.2 on 2022-02-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0009_alter_dimension_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='is_paid',
            new_name='payment_status',
        ),
    ]
