# Generated by Django 4.0.2 on 2022-03-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0010_rename_is_paid_expense_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Payee',
        ),
    ]
