# Generated by Django 4.0.1 on 2022-03-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0011_delete_expense_delete_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
