# Generated by Django 4.0.1 on 2022-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0013_dimension_delete_on_dimension_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimension',
            old_name='delete_on',
            new_name='deleted_on',
        ),
        migrations.AddField(
            model_name='project',
            name='delete_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
