# Generated by Django 4.0.2 on 2022-03-01 11:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimension', '0011_delete_expense_delete_payee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('phoneNumber', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('P', 'Paid'), ('R', 'Recieved'), ('PE', 'Pending'), ('NA', 'No Status')], default='N', max_length=2)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.payee')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dimension.project')),
            ],
        ),
    ]
