# Generated by Django 4.0.1 on 2022-03-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_payee_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='delete_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
