# Generated by Django 4.0.2 on 2022-07-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_companyuser_email_and_more'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsheading',
            name='organization',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
    ]
