# Generated by Django 4.0.2 on 2022-07-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_companyuser_email_and_more'),
        ('settings', '0002_termsheading_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsheading',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
    ]
