# Generated by Django 4.0.2 on 2022-07-16 07:09

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_termsheading_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='termscontent',
            name='content',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
