# Generated by Django 4.0.2 on 2022-07-16 12:27

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_termscontent_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termscontent',
            name='content',
        ),
        migrations.AddField(
            model_name='termsheading',
            name='content',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
