# Generated by Django 4.0.2 on 2022-07-16 15:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_remove_termscontent_content_termsheading_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsheading',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
