# Generated by Django 4.0.2 on 2022-07-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_termsheading_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermsContent',
        ),
    ]
