# Generated by Django 4.0.2 on 2022-07-16 22:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_delete_termscontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsheading',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
