# Generated by Django 4.0.2 on 2022-07-16 22:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_companyuser_email_and_more'),
        ('settings', '0009_alter_termsheading_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsheading',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='termsheading',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
    ]
