# Generated by Django 4.0.2 on 2022-10-20 07:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('authentication', '0021_alter_companyuser_location'),
        ('estimator', '0022_alter_projecttermsandconditions_options'),
        ('settings', '0010_alter_termsheading_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermsHeading',
            new_name='OrganizationTNC',
        ),
    ]
