# Generated by Django 4.0.7 on 2022-10-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_rename_termsheading_organizationtnc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationtnc',
            options={'verbose_name': 'Organization TNC', 'verbose_name_plural': 'Organization TNCs'},
        ),
    ]
