# Generated by Django 4.0.2 on 2022-05-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='payee',
            name='updated_on',
        ),
    ]
