# Generated by Django 3.2.16 on 2023-01-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payee',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
