# Generated by Django 4.0.1 on 2022-03-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expense_delete_on_expense_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
