# Generated by Django 3.2.16 on 2023-02-01 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_alter_payee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
