# Generated by Django 4.0.1 on 2022-03-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_rename_is_delete_expense_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='delete_on',
            new_name='deleted_on',
        ),
    ]
