# Generated by Django 4.2.7 on 2023-11-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='access_level',
            field=models.CharField(choices=[('ORG_ADM', 'Organization Admin'), ('ORG_MGM', 'Organization Management'), ('ORG_USR', 'Organization User')], default='SITE_USR', max_length=8, null=True),
        ),
    ]
