# Generated by Django 4.0.2 on 2022-05-30 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0002_client_organization'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_and_company.companydetail'),
        ),
    ]
