# Generated by Django 4.2.2 on 2023-11-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_companyuser_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.companyuser',),
        ),
    ]
