# Generated by Django 4.0.2 on 2022-05-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_organization_delete_customuseradmin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='manager_name',
        ),
    ]
