# Generated by Django 4.0.2 on 2022-06-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_name_organization_manager_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SITE_SU', 'SITE SUPERUSER'), ('SITE_USR', 'SITE USER'), ('ORG_ADM', 'ORGANIZATION ADMINISTRATOR'), ('ORG_USR', 'ORGANIZATION USER')], default='NS', max_length=8)),
            ],
        ),
    ]
