# Generated by Django 4.0.2 on 2022-06-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_accesslevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='access_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.accesslevel'),
        ),
    ]
