# Generated by Django 4.0.2 on 2022-06-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_companyuser_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='access_level',
            field=models.CharField(choices=[('SITE_SU', 'SITE SUPERUSER'), ('SITE_USR', 'SITE USER'), ('ORG_ADM', 'ORGANIZATION ADMINISTRATOR'), ('ORG_USR', 'ORGANIZATION USER')], default='NS', max_length=8, null=True),
        ),
        migrations.DeleteModel(
            name='AccessLevel',
        ),
    ]
