# Generated by Django 4.0.2 on 2022-06-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_companyuser_access_level_delete_accesslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='access_level',
            field=models.CharField(choices=[('SITE_SU', 'SITE SUPERUSER'), ('SITE_USR', 'SITE USER'), ('ORG_ADM', 'ORGANIZATION ADMINISTRATOR'), ('ORG_USR', 'ORGANIZATION USER')], default='SITE_USR', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
    ]
