# Generated by Django 4.0.2 on 2022-06-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_companyuser_access_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='access_level',
            field=models.CharField(choices=[('SITE_USR', 'SITE USER'), ('ORG_ADM', 'ORGANIZATION ADMINISTRATOR'), ('ORG_USR', 'ORGANIZATION USER')], default='SITE_USR', max_length=8, null=True),
        ),
    ]
