# Generated by Django 4.0.2 on 2022-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_companyuser_access_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='companyuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='first_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='last_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='username',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
