# Generated by Django 4.0.2 on 2022-07-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_companyuser_options_alter_companyuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
