# Generated by Django 4.0.2 on 2022-07-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_companyuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='is_staff',
        ),
    ]
