# Generated by Django 4.0.2 on 2022-07-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_companyuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
