# Generated by Django 4.0.2 on 2022-07-10 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_companyuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 12, 24, 26, 697475, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
