# Generated by Django 4.0.2 on 2022-07-10 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_companyuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='phoneNumber',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
