# Generated by Django 4.0.6 on 2022-08-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_companyuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
