# Generated by Django 4.0.2 on 2022-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_companyuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
