# Generated by Django 4.0.2 on 2022-10-20 05:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_companyuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='location',
            field=django_countries.fields.CountryField(blank=True, default='IN', max_length=2, null=True),
        ),
    ]
