# Generated by Django 3.2.16 on 2023-01-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_companyuser_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyuser',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
