# Generated by Django 3.2.16 on 2023-02-01 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20230131_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Phone number'),
        ),
    ]
