# Generated by Django 4.0.10 on 2023-06-18 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20230201_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
