# Generated by Django 4.0.10 on 2023-06-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_organization_registered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
