# Generated by Django 4.0.10 on 2023-08-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_organization_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bank_account_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_account_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_branch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_ifsc_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='gstin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
