# Generated by Django 4.0.10 on 2023-08-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_organization_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='gstin',
            new_name='gstn',
        ),
    ]
