# Generated by Django 4.0.10 on 2023-08-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_rename_gstin_organization_gstn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='bank_account_name',
            new_name='bank_account_holder_name',
        ),
    ]
