# Generated by Django 4.0.10 on 2023-08-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_rename_bank_account_name_organization_bank_account_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='bank_account_number',
            field=models.CharField(default='', max_length=18),
        ),
    ]
