"""
Django settings for Dimention_Measure project.
Generated by 'django-admin startproject' using Django 4.0.2.
For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from dotenv import load_dotenv
import logging
import os
import pymysql
from pathlib import Path
import re

from django.core.validators import RegexValidator

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

ADMINS = [
    ("Aditya Agarwal", "aditya.ag1234@gmail.com"),
    ("Nilesh Kumar Mandal", "s.nileshkm@gmail.com"),
]

ALLOWED_HOSTS = [
    "0.tcp.in.ngrok.io",
    "127.0.0.1",
    "0.tcp.ngrok.io",
    "localhost",
    "0.0.0.0",
    "13.234.231.51",
    "3.6.80.190",
    os.getenv("HOST_IP"),
    "*"
]

CSRF_TRUSTED_ORIGINS = [
    "https://adiagarwalrock-literate-computing-54wvrp9r7v634xpj-8000.preview.app.github.dev"
]

AUTH_USER_MODEL = "authentication.CompanyUser"

# Application definition
INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_quill',
    'ckeditor',
    'django_countries',
    'dimension',
    'client_and_company',
    'authentication',
    # 'expense',
    'estimator',
    'settings',
    'core',
]

# For django-admin-interface installed app
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "db_cache_table",
    },
}


STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStoage'

WSGI_APPLICATION = 'Dimention_Measure.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


# if DEBUG == False:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

print("Database Connected...")


CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# for supplying site over Https ONLY = True
# SECURE_SSL_REDIRECT = False

SESSION_COOKIE_SECURE = False
SECURE_HSTS_PRELOAD = True
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
