"""
Django settings for Dimention_Measure project.
Generated by 'django-admin startproject' using Django 4.0.2.
For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from dotenv import load_dotenv
import os
import pymysql
from pathlib import Path

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "0.tcp.in.ngrok.io",
    "127.0.0.1",
    "localhost",
    "0.0.0.0",
    "13.234.231.51",
    "3.6.80.190",
    os.getenv("HOST_IP"),
]

CSRF_TRUSTED_ORIGINS = [
    "http://3.6.80.190"
]

# Application definition
INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_quill',
    'ckeditor',
    'django_countries',
    'dimension',
    'client_and_company',
    'authentication',
    # 'expense',
    'estimator',
    'settings',
    'core',
]

# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = os.getenv("EMAIL_ID")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PWD")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "db_cache_table",
    },
}
print("Cache Enabled...")
print("\tCache Backend: ", CACHES["default"]["BACKEND"])


STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

WSGI_APPLICATION = 'Dimention_Measure.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('RDS_DB_NAME'),
        'USER': os.getenv('RDS_USERNAME'),
        'PASSWORD': os.getenv('RDS_PASSWORD'),
        'HOST': os.getenv('RDS_HOSTNAME'),
        'PORT': os.getenv('RDS_PORT'),
    }
}
print("Database Connected...")
