"""
Django settings for Dimention_Measure project.
Generated by 'django-admin startproject' using Django 4.0.2.
For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from dotenv import load_dotenv
from django.core.validators import RegexValidator
import logging
import os
from pathlib import Path
import pymysql
import re


BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=dotenv_path)

ENV = os.getenv("ENV")

if ENV == "prod":
    print("***************************************")
    print("")
    print("Initializing with Production Settings")
    print("")
    print("***************************************")
    from .prod_settings import *

elif ENV == "dev":
    print("***************************************")
    print("")
    print("Initializing with Development Settings")
    print("")
    print("***************************************")
    from .dev_settings import *
