# Generated by Django 4.0.2 on 2022-05-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='updated_on',
        ),
    ]
