# Generated by Django 4.0.2 on 2022-05-30 21:53

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('authentication', '0002_companyuser_organization'),
        ('client_and_company', '0002_client_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyDetail',
            new_name='Organization',
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization',
                     'verbose_name_plural': 'Organizations'},
        ),
    ]
