# Generated by Django 4.0.2 on 2022-05-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0002_remove_client_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='compan_name',
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client_and_company.companydetail'),
        ),
    ]
