# Generated by Django 4.0.2 on 2022-05-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0003_rename_companydetail_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
    ]
