# Generated by Django 4.0.2 on 2022-05-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0004_companydetail_compan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='compan_name',
            field=models.CharField(max_length=255),
        ),
    ]
