# Generated by Django 4.0.2 on 2022-05-31 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_organization_delete_customuseradmin_and_more'),
        ('client_and_company', '0004_alter_organization_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
