# Generated by Django 4.0.2 on 2022-05-31 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_name_organization_manager_name'),
        ('client_and_company', '0005_alter_client_organization_delete_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
    ]
