# Generated by Django 4.0.2 on 2022-05-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0005_alter_companydetail_compan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetail',
            old_name='compan_name',
            new_name='company_name',
        ),
    ]
