# Generated by Django 3.2.16 on 2023-01-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0007_client_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
