# Generated by Django 4.0.10 on 2023-06-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0009_auto_20230201_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
