# Generated by Django 4.0.10 on 2023-08-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0011_client_pan_number_client_project_address_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='pan_number',
            new_name='gstn',
        ),
    ]
