# Generated by Django 4.0.10 on 2023-08-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0012_rename_pan_number_client_gstn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='gstn',
            new_name='pan_number',
        ),
    ]
