# Generated by Django 4.0.10 on 2023-08-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0013_rename_gstn_client_pan_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='pan_number',
            new_name='tax_id',
        ),
    ]
