# Generated by Django 4.0.10 on 2023-08-14 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the project', max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the project was created')),
                ('is_deleted', models.BooleanField(default=False, help_text='Check to soft Delete the project')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Date and time when the project was deleted', null=True)),
                ('author', models.ForeignKey(help_text='User who created the project', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('length_feet', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('length_inches', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('width_feet', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('width_inches', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimension.project')),
            ],
        ),
    ]
