# Generated by Django 4.2.7 on 2023-11-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='length_feet',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='length_inches',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='width_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of the project', max_length=30),
        ),
    ]
