# Generated by Django 4.0.2 on 2022-05-30 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimension.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
