# Generated by Django 4.0.2 on 2022-05-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='updated_on',
        ),
    ]
