# Generated by Django 4.0.2 on 2022-02-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dimension.project'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='length',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='rate',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='sqft',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='sqm',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
