# Generated by Django 4.0.2 on 2022-05-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0002_remove_dimension_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated_on',
        ),
    ]
