# Generated by Django 4.2.7 on 2023-11-21 04:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dimension', '0002_alter_dimension_length_feet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='length_feet',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='length_inches',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='dimension.project'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='width_feet',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(help_text='User who created the project', on_delete=django.db.models.deletion.CASCADE, related_name='dimension_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Check to soft delete the project'),
        ),
    ]
