# Generated by Django 4.0.2 on 2022-07-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0002_alter_dimension_project_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
