# Generated by Django 4.2.2 on 2023-12-31 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dimension', '0003_alter_dimension_length_feet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Collection', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Description of the Collection', max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the Collection was created')),
                ('is_deleted', models.BooleanField(default=False, help_text='Check to soft delete the Collection')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Date and time when the Collection was deleted', null=True)),
                ('author', models.ForeignKey(help_text='User who created the Collection', on_delete=django.db.models.deletion.CASCADE, related_name='dimension_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dimension.collection'),
        ),
    ]
