# Generated by Django 4.0.2 on 2022-07-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0003_alter_dimension_amount_alter_dimension_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
