# Generated by Django 4.0.2 on 2022-02-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0004_dimension_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimension',
            old_name='created_on',
            new_name='updated_on',
        ),
    ]
