# Generated by Django 3.2.16 on 2022-12-24 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dimension', '0004_alter_dimension_amount_alter_dimension_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(help_text='User who created the project', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the project was created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted_on',
            field=models.DateTimeField(blank=True, help_text='Date and time when the project was deleted', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the project', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is the project deleted?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of the project', max_length=255, unique=True),
        ),
    ]
