# Generated by Django 4.2.2 on 2023-12-31 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dimension', '0004_alter_project_options_collection_project_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='author',
            field=models.ForeignKey(blank=True, default=None, help_text='User who created the dimension', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimension_dimensions', to=settings.AUTH_USER_MODEL),
        ),
    ]
