# Generated by Django 3.2.16 on 2023-01-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0005_auto_20221225_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of the project', max_length=30, unique=True),
        ),
    ]
