# Generated by Django 4.0.10 on 2023-07-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0006_auto_20230131_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='length_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dimension',
            name='length_inches',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='dimension',
            name='width_feet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='width_inches',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Check to soft Delete the project'),
        ),
    ]
