# Generated by Django 4.0.10 on 2023-07-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0007_dimension_length_feet_dimension_length_inches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='length',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='width',
        ),
        migrations.AlterField(
            model_name='dimension',
            name='length_feet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='width_feet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
