# Generated by Django 4.0.1 on 2022-03-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0012_project_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='delete_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
