# Generated by Django 4.0.1 on 2022-03-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0014_rename_delete_on_dimension_deleted_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='delete_on',
            new_name='deleted_on',
        ),
    ]
