# Generated by Django 4.0.2 on 2022-06-17 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitemdescription',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.unit'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
