# Generated by Django 4.0.2 on 2022-03-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='roomitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomitem',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='roomitem',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='roomitemdescription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='roomitemdescription',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='roomitemdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
