# Generated by Django 4.2.2 on 2023-11-26 10:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_alter_estimate_discount_alter_estimate_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='discount',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='rate',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='sqft',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='sqm',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0'), max_digits=20, null=True),
        ),
    ]
