# Generated by Django 4.0.2 on 2022-07-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0003_estimate_length_estimate_sqft_estimate_sqm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
