# Generated by Django 4.0.2 on 2022-07-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0004_estimate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('AMT', 'Amount'), ('PCT', 'Percentage')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='roomitemdescription',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
