# Generated by Django 4.0.2 on 2022-03-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0004_project_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
