# Generated by Django 4.0.2 on 2022-07-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0006_alter_estimate_amount_alter_estimate_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='discount_type',
        ),
        migrations.AddField(
            model_name='project',
            name='discount_in_percentage',
            field=models.BooleanField(default=False),
        ),
    ]
