# Generated by Django 4.0.2 on 2022-03-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0006_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
