# Generated by Django 4.0.2 on 2022-07-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0007_remove_project_discount_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='discount_in_percentage',
        ),
    ]
