# Generated by Django 4.0.2 on 2022-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0008_remove_project_discount_in_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
