# Generated by Django 4.0.2 on 2022-03-30 21:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0008_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='estimate',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estimate',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
