# Generated by Django 4.0.2 on 2022-03-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0009_client_phonenumber_estimate_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
