# Generated by Django 4.0.2 on 2022-07-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0009_alter_project_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
