# Generated by Django 4.0.2 on 2022-07-10 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('estimator', '0010_estimate_discount_alter_project_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.unit'),
        ),
    ]
