# Generated by Django 4.0.2 on 2022-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0011_estimate_rate_estimate_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
