# Generated by Django 4.0.2 on 2022-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0012_alter_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
