# Generated by Django 4.0.2 on 2022-07-11 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('estimator', '0012_alter_estimate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.unit'),
        ),
    ]
