# Generated by Django 4.0.2 on 2022-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0013_alter_estimate_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitemdescription',
            name='working',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roomitemdescription',
            name='description',
            field=models.TextField(),
        ),
    ]
