# Generated by Django 4.0.2 on 2022-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0014_roomitemdescription_working_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitemdescription',
            name='working',
            field=models.TextField(null=True),
        ),
    ]
