# Generated by Django 4.0.2 on 2022-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0015_alter_roomitemdescription_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitemdescription',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
