# Generated by Django 4.0.2 on 2022-07-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0016_alter_roomitemdescription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitemdescription',
            name='working',
            field=models.TextField(blank=True, null=True),
        ),
    ]
