# Generated by Django 4.0.2 on 2022-04-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0017_alter_client_name_alter_client_town_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
