# Generated by Django 4.0.2 on 2022-07-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0017_alter_roomitemdescription_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomitemdescription',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='roomitemdescription',
            name='unit',
        ),
    ]
