# Generated by Django 4.0.2 on 2022-07-17 11:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_termsheading_content_and_more'),
        ('estimator', '0018_remove_roomitemdescription_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('org_terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.termsheading')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.project')),
            ],
        ),
    ]
