# Generated by Django 4.0.2 on 2022-04-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0018_alter_client_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.IntegerField(blank=True, default=0, max_length=5),
        ),
    ]
