# Generated by Django 4.0.2 on 2022-04-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0019_alter_client_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.IntegerField(max_length=5),
        ),
    ]
