# Generated by Django 4.0.2 on 2022-07-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0019_projecttermsandconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='description',
        ),
    ]
