# Generated by Django 4.0.2 on 2022-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0020_alter_client_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
