# Generated by Django 4.0.2 on 2022-07-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_termsheading_content_and_more'),
        ('estimator', '0020_remove_estimate_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttermsandconditions',
            unique_together={('project', 'org_terms')},
        ),
    ]
