# Generated by Django 4.0.6 on 2022-08-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0021_alter_projecttermsandconditions_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttermsandconditions',
            options={'verbose_name': 'Project TNC', 'verbose_name_plural': 'Project TNC'},
        ),
    ]
