# Generated by Django 4.0.7 on 2022-10-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0022_alter_projecttermsandconditions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttermsandconditions',
            options={'verbose_name': 'Project TNC', 'verbose_name_plural': 'Project TNCs'},
        ),
    ]
