# Generated by Django 4.0.2 on 2022-04-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0022_unit_alter_project_name_estimate_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimator.unit'),
        ),
    ]
