# Generated by Django 4.0.2 on 2022-04-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0023_alter_estimate_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitemdescription',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimator.unit'),
        ),
    ]
