# Generated by Django 4.0.2 on 2022-04-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0024_roomitemdescription_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='unit',
        ),
    ]
