# Generated by Django 4.0.8 on 2023-02-05 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0024_auto_20230131_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
