# Generated by Django 4.0.2 on 2022-04-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0026_companydetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyDetails',
            new_name='CompanyDetail',
        ),
    ]
