# Generated by Django 4.0.2 on 2022-04-24 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0027_rename_companydetails_companydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TermsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.termsheading')),
            ],
        ),
    ]
