# Generated by Django 4.0.2 on 2022-05-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0028_termsheading_termscontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_on',
        ),
        migrations.DeleteModel(
            name='TermsContent',
        ),
        migrations.DeleteModel(
            name='TermsHeading',
        ),
    ]
