# Generated by Django 4.0.2 on 2022-05-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_and_company', '0002_remove_client_updated_on'),
        ('estimator', '0029_remove_client_updated_on_remove_estimate_updated_on_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_and_company.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
